import type { DoorDef, HubDef, ItemDef, ItemId } from '../types'

export const ITEMS: Record<ItemId, ItemDef> = {
  vial_empty: {
    id: 'vial_empty',
    name: 'Empty Vial',
    kind: 'gear',
    desc: 'A throat of glass. Waiting.',
  },
  vial_drop: {
    id: 'vial_drop',
    name: 'Vial (Drop)',
    kind: 'gear',
    desc: 'One Drop of Oasis Sap. Heat and honey. Life.',
  },
  scrap: {
    id: 'scrap',
    name: 'Scrap',
    kind: 'gear',
    desc: 'Bent metal. Wire. Things that cut or trade.',
  },
  glints: {
    id: 'glints',
    name: 'Glints',
    kind: 'currency',
    desc: 'Chips of spent amber. Offerings, and coin, depending on who is watching.',
  },
  scrip: {
    id: 'scrip',
    name: 'Cartel Scrip',
    kind: 'currency',
    desc: 'Paper that only Ironwood loves.',
  },
  shiv: {
    id: 'shiv',
    name: 'Bleed Shiv',
    kind: 'weapon',
    slot: 'weapon',
    offhand: 'blade',
    strike: 2,
    desc: 'A vat-edge ground to a point. Strike 2. Equip it to meet a throat, not a hymn.',
  },
  strider_bit: {
    id: 'strider_bit',
    name: 'Strider Bit',
    kind: 'key',
    desc: 'Stolen. Still warm from the mouth.',
  },
  ceremonial_cloth: {
    id: 'ceremonial_cloth',
    name: 'Vessel Cloth',
    kind: 'garment',
    slot: 'garment',
    perk: 'Outside the Vessel door: Cartel eyes read a cup. Cartel Heat gains are 1 lower, and you can walk past a Cartel check. A close look can see through it.',
    desc: 'Gold-thread lie. Garment, not Armor — Seekers bow to it, and a real shell can be worn beside it. It does not add Shell. Equip it and the desert reads a cup.',
  },
  overseer_chip: {
    id: 'overseer_chip',
    name: 'Overseer Chip',
    kind: 'key',
    desc: 'Valerius does not know it is gone. Yet.',
  },
  ossa_token: {
    id: 'ossa_token',
    name: "Ossa's Knot",
    kind: 'gear',
    slot: 'head',
    desc: 'Stilt-cord knotted twice. A headband. She is alive. She remembers.',
  },
  kallik_mark: {
    id: 'kallik_mark',
    name: "Kallik's Mark",
    kind: 'key',
    desc: "A burned map-scar. Points at Red Maw whether you want it to or not.",
  },
  kohl_smear: {
    id: 'kohl_smear',
    name: "Sybella's Kohl",
    kind: 'key',
    desc: 'Her thumb, dark with kohl, pressed to your brow. The old way of saying: the sand has seen this one.',
  },
  false_vessel: {
    id: 'false_vessel',
    name: 'False Vessel Sigil',
    kind: 'key',
    desc: 'You walked as a cup. The desert noticed.',
  },
  cache_map: {
    id: 'cache_map',
    name: 'Cache Scratch',
    kind: 'key',
    desc: "Not a map. A drunk's directions to Kallik's hole.",
  },
  wrench: {
    id: 'wrench',
    name: 'Oversized Wrench',
    kind: 'weapon',
    slot: 'weapon',
    strike: 3,
    desc: "Jaxson's steel. Strike 3. Hotwires Striders. Pries bolts, wire, and lies. Equip it if you mean to swing.",
  },
  rusted_dagger: {
    id: 'rusted_dagger',
    name: 'Rusted Dagger',
    kind: 'weapon',
    slot: 'weapon',
    offhand: 'blade',
    strike: 2,
    desc: 'A Threshold kitchen knife that learned a worse job. Strike 2. Equip it to make the worse job count.',
  },
  silas_tip: {
    id: 'silas_tip',
    name: "Silas's Tip",
    kind: 'key',
    desc: 'Shade-cut scratch. Stray-to-stray. Spend it or save it.',
  },
  oram_map: {
    id: 'oram_map',
    name: "Oram's Map",
    kind: 'key',
    desc: "Feed-pencil heading to Kallik's second rib. Oram will deny it.",
  },
  ironwood_baton: {
    id: 'ironwood_baton',
    name: 'Shock Baton',
    kind: 'weapon',
    slot: 'weapon',
    offhand: 'club',
    strike: 4,
    desc: 'Ironwood issue. Strike 4. Still warm from a clerk who loved a ledger more than a throat.',
  },
  needle_knife: {
    id: 'needle_knife',
    name: 'Needle Knife',
    kind: 'weapon',
    slot: 'weapon',
    offhand: 'blade',
    strike: 3,
    desc: "A trader's shelf. Strike 3. Thin. Mean. Scrapes hard resin.",
  },
  scav_wrap: {
    id: 'scav_wrap',
    name: 'Scav Wrap',
    kind: 'armor',
    slot: 'armor',
    shell: 2,
    desc: 'Wire and rag, wrapped twice by someone who lived. Shell 2. The step between bare shoulders and a Dust Cloak.',
  },
  dust_cloak: {
    id: 'dust_cloak',
    name: 'Dust Cloak',
    kind: 'armor',
    slot: 'cloak',
    shell: 2,
    perk: 'Worn, it lets you skip a road fight before the first exchange, and it eats a hunter\'s glance.',
    desc: 'Canvas that has outlived three owners. Cloak slot, Shell 2. Hides a silhouette. Does not hide Heat.',
  },
  hide_wrap: {
    id: 'hide_wrap',
    name: 'Hound Hide',
    kind: 'armor',
    slot: 'armor',
    shell: 4,
    desc: 'Resin-jawed scrap from a Shard-Hound that lost. Shell 4. Wear it and the next glance slides.',
  },
  salve: {
    id: 'salve',
    name: 'Resin Salve',
    kind: 'gear',
    desc: 'A thumb of camp resin. Binds a cut. Not a Drop. Health, not sap.',
  },
  head_wrap: {
    id: 'head_wrap',
    name: 'Head Wrap',
    kind: 'armor',
    slot: 'head',
    shell: 1,
    desc: 'Layered rag wound over the head and across the mouth. Head slot, Shell 1. Keeps grit out of your eyes and mouth.',
  },
  shin_wraps: {
    id: 'shin_wraps',
    name: 'Shin Wraps',
    kind: 'armor',
    slot: 'legs',
    shell: 1,
    perk: 'Run gets away 10 in 100 more often.',
    desc: 'Hide strips bound from ankle to knee. Legs slot, Shell 1.',
  },
  hide_gloves: {
    id: 'hide_gloves',
    name: 'Hide Gloves',
    kind: 'armor',
    slot: 'hands',
    perk: 'Pulling a tick off costs no attack. You pull it and strike in the same exchange.',
    desc: 'Stiff hide gloves with the fingertips worn through. Hands slot.',
  },
  scrap_buckler: {
    id: 'scrap_buckler',
    name: 'Scrap Buckler',
    kind: 'armor',
    slot: 'offhand',
    offhand: 'shield',
    shell: 1,
    desc: 'A hubcap of riveted scrap with a strap on the back. Off hand only, Shell 1.',
  },
  sinew_cord: {
    id: 'sinew_cord',
    name: 'Sinew Cord',
    kind: 'gear',
    desc: 'A coil of dried sinew, strong enough to stitch canvas. A crafting material.',
  },
  scav_pack: {
    id: 'scav_pack',
    name: 'Scav Pack',
    kind: 'key',
    bag: 14,
    desc: 'A stitched canvas pack with a cord strap. Carries 14.',
  },
  hauler_pack: {
    id: 'hauler_pack',
    name: 'Hauler Pack',
    kind: 'key',
    bag: 20,
    desc: 'A Cartel hauler frame with a canvas sack lashed to it. Carries 20.',
  },
  seeker_extractor: {
    id: 'seeker_extractor',
    name: 'Seeker Extractor',
    kind: 'weapon',
    slot: 'weapon',
    strike: 3,
    perk: 'In an Amber Husk fight, once: Draw resin — take scrap and a little Sap without shattering the core, or cut the Seeker\'s siphon if one is walking the husk.',
    desc: 'A thin Seeker blade forged to draw living heat and liquefy resin seals under husk plates without shattering the core. Main hand, Strike 3.',
  },
}

export const DOORS: Record<string, DoorDef> = {
  prisoner: {
    id: 'prisoner',
    title: 'Ironwood Break',
    role: 'Prisoner',
    place: 'Ironwood Camp-04',
    epithet: 'the Bleed-Cut',
    blurb:
      'Holding pens. Cartel Scrip only. The Great Bleed is about to hit. You wake with blood on the back of your head and no faction\'s kit. Jaxson hotwires. Kaelen the Sifter, once, sells rumors at the Wire.',
    sap: 4,
    heat: { cartel: 3, seekers: 0, strays: 1 },
    items: { scrip: 2 },
    flags: { origin: 'prisoner', campInside: true, penniless: true },
    sceneId: 'open:prisoner',
    hubId: 'camp04',
  },
  outcast: {
    id: 'outcast',
    title: 'First Drop',
    role: 'Outcast',
    place: 'Bleached Spine',
    epithet: 'the Noon-Empty',
    blurb:
      'Face-down in the sand, empty pockets, a brand on your face. Silas tosses you an empty vial: earn your keep. Get a Drop before noon.',
    sap: 2,
    heat: { cartel: 0, seekers: 1, strays: 2 },
    items: {},
    flags: { origin: 'outcast', noonEmpty: true, silasTip: true },
    sceneId: 'open:outcast',
    hubId: 'spine',
  },
  vessel: {
    id: 'vessel',
    title: 'Vessel',
    role: 'Cult',
    place: 'Outer Threshold',
    epithet: 'the False Cup',
    blurb:
      'Cloth on. Dagger under it. Oram’s map in the sleeve. Thalia already loves you too much. The Seekers love a full cup. They hate a liar.',
    sap: 5,
    heat: { cartel: 0, seekers: 3, strays: 0 },
    items: {
      ceremonial_cloth: 1,
      false_vessel: 1,
      strider_bit: 1,
      vial_drop: 1,
      rusted_dagger: 1,
      oram_map: 1,
    },
    flags: { origin: 'vessel', fakeVessel: true, thaliaPressure: true },
    sceneId: 'open:vessel',
    hubId: 'threshold',
  },
}

export const HUBS: Record<string, HubDef> = {
  camp04: {
    id: 'camp04',
    name: 'Ironwood Camp-04',
    region: 'Cartel wire',
    blurb: 'Loud polluted labor camp. Razor-wire. Steam-vents. The Bleed never dries.',
    defaultScene: 'camp:cages',
    places: [
      { id: 'pens', name: 'Holding Pens', sceneId: 'camp:cages' },
      { id: 'yard', name: 'Bleed Yard', sceneId: 'camp:yard' },
      { id: 'vents', name: 'Steam Vents', sceneId: 'camp:vents' },
      { id: 'guard', name: 'Guard Station', sceneId: 'camp:guard' },
      { id: 'bay', name: 'Skiff Bay', sceneId: 'camp:bay' },
      { id: 'lean', name: "Jaxson's Stall", sceneId: 'camp:lean' },
      { id: 'tower', name: 'Overseer', sceneId: 'camp:tower' },
      { id: 'wire', name: 'The Wire', sceneId: 'camp:wire' },
    ],
    hungerHook: {
      label: 'Take the rumor into the dunes',
      sub: 'Red Maw: days east. Four roads from the pens. Then the Hunger.',
      sceneId: 'ch1:leave',
      show: { flag: 'hungerKnown' },
    },
    mawLegs: 4,
    mawNote: 'Red Maw is days beyond the Wire. Cartel hinterland: the farthest door from the Maw.',
  },
  spine: {
    id: 'spine',
    name: 'Bleached Spine',
    region: 'Stray country',
    blurb: "A ridge like a dead animal's back. Noon never ends here.",
    defaultScene: 'spine:ridge',
    places: [
      { id: 'ridge', name: 'Noon Spine', sceneId: 'spine:ridge' },
      { id: 'shade', name: "Silas's Shade", sceneId: 'spine:shade' },
      { id: 'well', name: 'Dry Well', sceneId: 'spine:well' },
      { id: 'hound', name: 'Hound Sign', sceneId: 'spine:hound' },
    ],
    hungerHook: {
      label: 'Walk the Hunger toward Red Maw',
      sub: 'Red Maw: a hard day south. Closer than Ironwood. Not close.',
      sceneId: 'ch1:leave',
      show: { flag: 'hungerKnown' },
    },
    mawLegs: 2,
    mawNote: 'Red Maw is a hard day south. Stray country sits nearer the bite than Camp-04.',
  },
  threshold: {
    id: 'threshold',
    name: 'Outer Threshold',
    region: 'Seeker fringe',
    blurb: 'Where the cult still pretends the desert is a church.',
    defaultScene: 'thresh:court',
    places: [
      { id: 'court', name: 'Threshold Court', sceneId: 'thresh:court' },
      { id: 'cell', name: 'False Vessel Cell', sceneId: 'thresh:cell' },
      { id: 'sift', name: 'Cup-Shadow', sceneId: 'thresh:sift' },
      { id: 'paddock', name: 'Strider Paddock', sceneId: 'thresh:paddock' },
      { id: 'guard', name: 'Guard Post', sceneId: 'thresh:guard' },
    ],
    hungerHook: {
      label: 'Ride the stolen Strider into Hunger',
      sub: 'The Spire is sealed. What opens it is at Red Maw. Shortest Hunger-road.',
      sceneId: 'ch1:leave',
      show: { any: [{ flag: 'hungerKnown' }, { item: 'oram_map' }] },
    },
    mawLegs: 1,
    mawNote: 'The sealed Spire stands off the paddock. What opens it is at Red Maw, one short road west.',
  },
  redmaw: {
    id: 'redmaw',
    name: 'Red Maw Approach',
    region: 'The Hunger holds',
    blurb: 'Harder sand. Sybella hunting. The Maw breathes at night.',
    defaultScene: 'maw:rim',
    places: [
      { id: 'rim', name: 'Maw Rim', sceneId: 'maw:rim' },
      { id: 'market', name: 'Bone Market', sceneId: 'maw:market' },
      { id: 'stilt', name: 'Stilt Shade', sceneId: 'maw:stilt' },
      { id: 'smoke', name: 'Skiff Smoke', sceneId: 'maw:smoke' },
      { id: 'lip', name: 'Hollow Lip', sceneId: 'maw:lip' },
      { id: 'tuner', name: 'The Wreck', sceneId: 'maw:tuner' },
    ],
    hungerHook: {
      label: 'Under the jaw',
      sub: 'Hunger is open. Run, leave, or take the Hunger.',
      sceneId: 'ch2:stub',
      show: { flag: 'chapter1Done' },
    },
    mawLegs: 0,
    mawNote: 'Red Maw Approach. All three roads end here. The sealed Spire waits east, past the Threshold.',
  },
}
