import type { DoorDef, HubDef, ItemDef, ItemId } from '../types'

export const ITEMS: Record<ItemId, ItemDef> = {
  vial_empty: {
    id: 'vial_empty',
    name: 'Empty Vial',
    kind: 'gear',
    desc: 'A throat of glass. Waiting.',
  },
  vial_drop: {
    id: 'vial_drop',
    name: 'Vial (Drop)',
    kind: 'gear',
    desc: 'One Drop of Oasis Sap. Heat and honey. Life.',
  },
  scrap: {
    id: 'scrap',
    name: 'Scrap',
    kind: 'gear',
    desc: 'Bent metal. Wire. Things that cut or trade.',
  },
  glints: {
    id: 'glints',
    name: 'Glints',
    kind: 'currency',
    desc: 'Chips of spent amber. Dune money.',
  },
  scrip: {
    id: 'scrip',
    name: 'Cartel Scrip',
    kind: 'currency',
    desc: 'Paper that only Ironwood loves.',
  },
  shiv: {
    id: 'shiv',
    name: 'Bleed Shiv',
    kind: 'weapon',
    slot: 'weapon',
    bite: 2,
    desc: 'A vat-edge ground to a point. Bite 2. Equip it to meet a throat, not a hymn. Numbers compare gear — no dice.',
  },
  strider_bit: {
    id: 'strider_bit',
    name: 'Strider Bit',
    kind: 'key',
    desc: 'Stolen. Still warm from the mouth.',
  },
  ceremonial_cloth: {
    id: 'ceremonial_cloth',
    name: 'Vessel Cloth',
    kind: 'armor',
    slot: 'armor',
    hide: 1,
    desc: 'Gold-thread lie. Hide 1. Seekers bow to it. Equip it and the desert reads a cup. Numbers compare gear — no dice.',
  },
  overseer_chip: {
    id: 'overseer_chip',
    name: 'Overseer Chip',
    kind: 'key',
    desc: 'Valerius does not know it is gone. Yet.',
  },
  ossa_token: {
    id: 'ossa_token',
    name: "Ossa's Knot",
    kind: 'key',
    desc: 'Stilt-cord knotted twice. She is alive. She remembers.',
  },
  kallik_mark: {
    id: 'kallik_mark',
    name: "Kallik's Mark",
    kind: 'key',
    desc: "A burned map-scar. Points at Red Maw whether you want it to or not.",
  },
  kohl_smear: {
    id: 'kohl_smear',
    name: "Sybella's Kohl",
    kind: 'key',
    desc: 'She wiped her thumb on you. A claim.',
  },
  false_vessel: {
    id: 'false_vessel',
    name: 'False Vessel Sigil',
    kind: 'key',
    desc: 'You walked as a cup. The desert noticed.',
  },
  cache_map: {
    id: 'cache_map',
    name: 'Cache Scratch',
    kind: 'key',
    desc: "Not a map. A drunk's directions to Kallik's hole.",
  },
  wrench: {
    id: 'wrench',
    name: 'Oversized Wrench',
    kind: 'weapon',
    slot: 'weapon',
    bite: 3,
    desc: "Oil-Tooth's steel. Bite 3. Hotwires Striders. Pries bolts, wire, and lies. Equip it if you mean to swing. Numbers compare gear — no dice.",
  },
  rusted_dagger: {
    id: 'rusted_dagger',
    name: 'Rusted Dagger',
    kind: 'weapon',
    slot: 'weapon',
    bite: 2,
    desc: 'A Threshold kitchen knife that learned a worse job. Bite 2. Equip it to make the worse job count. Numbers compare gear — no dice.',
  },
  silas_tip: {
    id: 'silas_tip',
    name: "Silas's Tip",
    kind: 'key',
    desc: 'Shade-cut scratch. Stray-to-stray. Spend it or save it.',
  },
  oram_map: {
    id: 'oram_map',
    name: "Oram's Map",
    kind: 'key',
    desc: "Feed-pencil heading to Kallik's second rib. Oram will deny it.",
  },
  ironwood_baton: {
    id: 'ironwood_baton',
    name: 'Shock Baton',
    kind: 'weapon',
    slot: 'weapon',
    bite: 4,
    desc: 'Ironwood issue. Bite 4. Still warm from a clerk who loved a ledger more than a throat. Numbers compare gear — no dice.',
  },
  needle_knife: {
    id: 'needle_knife',
    name: 'Needle Knife',
    kind: 'weapon',
    slot: 'weapon',
    bite: 3,
    desc: "Kaelen's shelf. Bite 3. Thin. Mean. Cost, not charity. Numbers compare gear — no dice.",
  },
  dust_cloak: {
    id: 'dust_cloak',
    name: 'Dust Cloak',
    kind: 'armor',
    slot: 'armor',
    hide: 3,
    desc: 'Canvas that has outlived three owners. Hide 3. Hides a silhouette. Does not hide Heat. Numbers compare gear — no dice.',
  },
  hide_wrap: {
    id: 'hide_wrap',
    name: 'Hound Hide',
    kind: 'armor',
    slot: 'armor',
    hide: 4,
    desc: 'Resin-jawed scrap from a Shard-Hound that lost. Hide 4. Wear it and the next glance slides. Numbers compare gear — no dice.',
  },
}

export const DOORS: Record<string, DoorDef> = {
  prisoner: {
    id: 'prisoner',
    title: 'Ironwood Break',
    role: 'Prisoner',
    place: 'Ironwood Camp-04',
    epithet: 'the Bleed-Cut',
    blurb:
      'Holding pens. Cartel Scrip only. The Great Bleed is about to hit. Oil-Tooth hotwires the Strider. Kaelen the Sifter sells rumors — they are not your inside man.',
    sap: 4,
    heat: { cartel: 3, seekers: 0, strays: 1 },
    items: { scrip: 2 },
    flags: { origin: 'prisoner', campInside: true, penniless: true },
    sceneId: 'open:prisoner',
    hubId: 'camp04',
  },
  outcast: {
    id: 'outcast',
    title: 'First Drop',
    role: 'Outcast',
    place: 'Bleached Spine',
    epithet: 'the Noon-Empty',
    blurb:
      'Empty vial. Noon heat. Silas already sold you a shade-cut on credit. The Spine will collect — in sap, or in favors.',
    sap: 2,
    heat: { cartel: 0, seekers: 1, strays: 2 },
    items: { vial_empty: 1, silas_tip: 1 },
    flags: { origin: 'outcast', noonEmpty: true, silasTip: true },
    sceneId: 'open:outcast',
    hubId: 'spine',
  },
  vessel: {
    id: 'vessel',
    title: 'Vessel',
    role: 'Cult',
    place: 'Outer Threshold',
    epithet: 'the False Cup',
    blurb:
      'Cloth on. Dagger under it. Oram’s map in the sleeve. Thalia already loves you too much. The Seekers love a full cup. They hate a liar.',
    sap: 5,
    heat: { cartel: 0, seekers: 3, strays: 0 },
    items: {
      ceremonial_cloth: 1,
      false_vessel: 1,
      strider_bit: 1,
      vial_drop: 1,
      rusted_dagger: 1,
      oram_map: 1,
    },
    flags: { origin: 'vessel', fakeVessel: true, thaliaPressure: true },
    sceneId: 'open:vessel',
    hubId: 'threshold',
  },
}

export const HUBS: Record<string, HubDef> = {
  camp04: {
    id: 'camp04',
    name: 'Ironwood Camp-04',
    region: 'Cartel wire',
    blurb: 'Loud polluted labor camp. Razor-wire. Steam-vents. The Bleed never dries.',
    defaultScene: 'camp:cages',
    places: [
      { id: 'pens', name: 'Holding Pens', sceneId: 'camp:cages' },
      { id: 'yard', name: 'Bleed Yard', sceneId: 'camp:yard' },
      { id: 'vents', name: 'Steam Vents', sceneId: 'camp:vents' },
      { id: 'guard', name: 'Guard Station', sceneId: 'camp:guard' },
      { id: 'bay', name: 'Skiff Bay', sceneId: 'camp:bay' },
      { id: 'lean', name: "Oil-Tooth's Stall", sceneId: 'camp:lean' },
      { id: 'tower', name: 'Overseer', sceneId: 'camp:tower' },
      { id: 'wire', name: 'The Wire', sceneId: 'camp:wire' },
    ],
    hungerHook: {
      label: 'Take the rumor into the dunes',
      sub: 'First Spires: days south. Four roads from the pens. Then the Hunger.',
      sceneId: 'ch1:leave',
      show: { flag: 'hungerKnown' },
    },
    mawLegs: 4,
    mawNote: 'First Spires sit days beyond the Wire. Cartel hinterland — farthest from the Maw.',
  },
  spine: {
    id: 'spine',
    name: 'Bleached Spine',
    region: 'Stray country',
    blurb: "A ridge like a dead animal's back. Noon never ends here.",
    defaultScene: 'spine:ridge',
    places: [
      { id: 'ridge', name: 'Noon Spine', sceneId: 'spine:ridge' },
      { id: 'shade', name: "Silas's Shade", sceneId: 'spine:shade' },
      { id: 'well', name: 'Dry Well', sceneId: 'spine:well' },
      { id: 'hound', name: 'Hound Sign', sceneId: 'spine:hound' },
    ],
    hungerHook: {
      label: 'Walk the Hunger toward Red Maw',
      sub: 'First Spires: a hard day east-south. Closer than Ironwood. Not close.',
      sceneId: 'ch1:leave',
      show: { any: [{ flag: 'hungerKnown' }, { item: 'silas_tip' }] },
    },
    mawLegs: 2,
    mawNote: 'First Spires are a hard day east-south. Stray country sits nearer the bite than Camp-04.',
  },
  threshold: {
    id: 'threshold',
    name: 'Outer Threshold',
    region: 'Seeker fringe',
    blurb: 'Where the cult still pretends the desert is a church.',
    defaultScene: 'thresh:court',
    places: [
      { id: 'court', name: 'Threshold Court', sceneId: 'thresh:court' },
      { id: 'cell', name: 'False Vessel Cell', sceneId: 'thresh:cell' },
      { id: 'sift', name: 'Cup-Shadow', sceneId: 'thresh:sift' },
      { id: 'paddock', name: 'Strider Paddock', sceneId: 'thresh:paddock' },
      { id: 'guard', name: 'Guard Post', sceneId: 'thresh:guard' },
    ],
    hungerHook: {
      label: 'Ride the stolen Strider into Hunger',
      sub: 'First Spires: the paddock already faces them. Shortest Hunger-road.',
      sceneId: 'ch1:leave',
      show: { any: [{ flag: 'hungerKnown' }, { item: 'oram_map' }] },
    },
    mawLegs: 1,
    mawNote: 'First Spires stand off the paddock. Seeker fringe is the Maw’s doorstep.',
  },
  redmaw: {
    id: 'redmaw',
    name: 'Red Maw Approach',
    region: 'The Hunger holds',
    blurb: 'Harder sand. Sybella hunting. The Maw breathes at night.',
    defaultScene: 'maw:rim',
    places: [
      { id: 'rim', name: 'Maw Rim', sceneId: 'maw:rim' },
      { id: 'market', name: 'Bone Market', sceneId: 'maw:market' },
      { id: 'stilt', name: 'Stilt Shade', sceneId: 'maw:stilt' },
      { id: 'smoke', name: 'Skiff Smoke', sceneId: 'maw:smoke' },
      { id: 'lip', name: 'Hollow Lip', sceneId: 'maw:lip' },
    ],
    hungerHook: {
      label: 'The Walking Amber',
      sub: 'Chapter 2 — sealed for now. You are already at the bite.',
      sceneId: 'ch2:stub',
      show: { flag: 'chapter1Done' },
    },
    mawLegs: 0,
    mawNote: 'Red Maw Approach. The Spires are the teeth around you.',
  },
}
