import type { HubMapDef } from '../types'

export const HUB_MAPS: Record<string, HubMapDef> = {
  camp04: {
    hubId: 'camp04',
    ready: true,
    width: 100,
    height: 132,
    defaultNode: 'pens',
    blurb: 'Cartel wire. South is Maw-country — days away. First Spires are a rumor of distance. Walk the roads. No teleport.',
    maw: { x: 78, y: 124, label: 'Maw / dunes' },
    nodes: [
      { id: 'tower', name: 'Overseer', sceneId: 'camp:tower', x: 72, y: 11 },
      { id: 'guard', name: 'Guard Station', short: 'Guard', sceneId: 'camp:guard', x: 70, y: 30 },
      { id: 'vents', name: 'Steam Vents', short: 'Vents', sceneId: 'camp:vents', x: 34, y: 44 },
      { id: 'bay', name: 'Skiff Bay', sceneId: 'camp:bay', x: 80, y: 52 },
      { id: 'yard', name: 'Bleed Yard', short: 'Yard', sceneId: 'camp:yard', x: 28, y: 66 },
      { id: 'pens', name: 'Holding Pens', short: 'Pens', sceneId: 'camp:cages', x: 14, y: 90 },
      { id: 'lean', name: "Oil-Tooth's Stall", short: 'Stall', sceneId: 'camp:lean', x: 44, y: 88 },
      { id: 'wire', name: 'The Wire', sceneId: 'camp:wire', x: 74, y: 102, mawExit: true },
    ],
    edges: [
      { a: 'tower', b: 'guard' },
      { a: 'guard', b: 'vents' },
      { a: 'guard', b: 'bay' },
      { a: 'vents', b: 'yard' },
      { a: 'vents', b: 'bay' },
      { a: 'yard', b: 'pens' },
      { a: 'yard', b: 'lean' },
      { a: 'pens', b: 'lean' },
      { a: 'lean', b: 'bay' },
      { a: 'bay', b: 'wire', sap: 2 },
    ],
    sceneNode: {
      'camp:cages': 'pens',
      'camp:shiv': 'pens',
      'camp:yard': 'yard',
      'camp:vats': 'yard',
      'camp:vents': 'vents',
      'camp:lean': 'lean',
      'camp:jaxson': 'lean',
      'camp:jaxson-cache': 'lean',
      'camp:jaxson-drop': 'lean',
      'camp:guard': 'guard',
      'camp:sabotage': 'guard',
      'camp:bay': 'bay',
      'camp:tower': 'tower',
      'camp:valerius': 'tower',
      'camp:wire': 'wire',
      'camp:kaelen': 'wire',
      'camp:kaelen-rumors': 'wire',
      'camp:relic': 'wire',
      'camp:hunter': 'yard',
      'camp:forced': 'yard',
    },
  },
  spine: {
    hubId: 'spine',
    ready: true,
    width: 100,
    height: 120,
    defaultNode: 'ridge',
    blurb: 'Stray country. First Spires sit a hard day east-south — nearer than Ironwood, not a doorstep.',
    maw: { x: 86, y: 112, label: 'Maw-haze' },
    nodes: [
      { id: 'ridge', name: 'Noon Spine', short: 'Ridge', sceneId: 'spine:ridge', x: 30, y: 26 },
      { id: 'shade', name: "Silas's Shade", short: 'Shade', sceneId: 'spine:shade', x: 22, y: 58 },
      { id: 'well', name: 'Dry Well', sceneId: 'spine:well', x: 58, y: 46 },
      { id: 'hound', name: 'Hound Sign', short: 'Hounds', sceneId: 'spine:hound', x: 76, y: 78, mawExit: true },
    ],
    edges: [
      { a: 'ridge', b: 'shade' },
      { a: 'ridge', b: 'well' },
      { a: 'shade', b: 'well' },
      { a: 'well', b: 'hound', sap: 2 },
    ],
    sceneNode: {
      'spine:ridge': 'ridge',
      'spine:tip': 'ridge',
      'spine:shade': 'shade',
      'spine:silas': 'shade',
      'spine:silas-drop': 'shade',
      'spine:silas-cache': 'shade',
      'spine:well': 'well',
      'spine:kaelen': 'well',
      'spine:kaelen-rumors': 'well',
      'spine:hound': 'hound',
      'spine:valerius': 'hound',
      'spine:hunter': 'shade',
    },
  },
  threshold: {
    hubId: 'threshold',
    ready: true,
    width: 100,
    height: 120,
    defaultNode: 'court',
    blurb: 'Seeker fringe. First Spires already face the paddock. Shortest road of the three starts.',
    maw: { x: 58, y: 112, label: 'Hunger south' },
    nodes: [
      { id: 'court', name: 'Threshold Court', short: 'Court', sceneId: 'thresh:court', x: 50, y: 40 },
      { id: 'cell', name: 'False Vessel Cell', short: 'Cell', sceneId: 'thresh:cell', x: 20, y: 36 },
      { id: 'paddock', name: 'Strider Paddock', short: 'Paddock', sceneId: 'thresh:paddock', x: 48, y: 78, mawExit: true },
      { id: 'guard', name: 'Guard Post', short: 'Guard', sceneId: 'thresh:guard', x: 80, y: 48 },
    ],
    edges: [
      { a: 'court', b: 'cell' },
      { a: 'court', b: 'paddock' },
      { a: 'paddock', b: 'guard' },
      { a: 'court', b: 'guard', sap: 2 },
    ],
    sceneNode: {
      'thresh:court': 'court',
      'thresh:thalia': 'court',
      'thresh:cell': 'cell',
      'thresh:shrine': 'cell',
      'thresh:paddock': 'paddock',
      'thresh:oram': 'paddock',
      'thresh:guard': 'guard',
      'thresh:guard-talk': 'guard',
      'thresh:hunter': 'paddock',
    },
  },
  redmaw: {
    hubId: 'redmaw',
    ready: true,
    width: 100,
    height: 120,
    defaultNode: 'rim',
    blurb: 'You are at the bite. First Spires are the teeth. The Lip is the only road into the walking dark.',
    maw: { x: 88, y: 96, label: 'The Maw' },
    nodes: [
      { id: 'rim', name: 'Maw Rim', short: 'Rim', sceneId: 'maw:rim', x: 50, y: 48 },
      { id: 'market', name: 'Bone Market', short: 'Market', sceneId: 'maw:market', x: 22, y: 38 },
      { id: 'stilt', name: 'Stilt Shade', short: 'Stilts', sceneId: 'maw:stilt', x: 26, y: 74 },
      { id: 'smoke', name: 'Skiff Smoke', short: 'Smoke', sceneId: 'maw:smoke', x: 74, y: 36 },
      { id: 'lip', name: 'Hollow Lip', short: 'Lip', sceneId: 'maw:lip', x: 78, y: 78, mawExit: true },
    ],
    edges: [
      { a: 'rim', b: 'market' },
      { a: 'rim', b: 'stilt' },
      { a: 'rim', b: 'smoke' },
      { a: 'market', b: 'stilt' },
      { a: 'smoke', b: 'lip', sap: 2 },
    ],
    sceneNode: {
      'maw:rim': 'rim',
      'maw:sybella-shadow': 'rim',
      'maw:market': 'market',
      'maw:zafir': 'market',
      'maw:stilt': 'stilt',
      'maw:ossa': 'stilt',
      'maw:smoke': 'smoke',
      'maw:sybella': 'smoke',
      'maw:lip': 'lip',
    },
  },
}
